repos:
  - repo: local
    hooks:
      - id: style
        name: style
        language: system
        entry: make style

  - repo: local
    hooks:
      - id: lock
        name: lock
        language: system
        entry: make check-lock
