name: check-lock-and-lint

on: [pull_request]

env:
  UV_VERSION: "0.9.2"

jobs:
  check-lock-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: "true"

      - name: Set up Python in pyproject.toml
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Validate uv.lock
        run: |
          uv lock --check

      - name: Check Lint (ruff)
        run: |
          make quality
